Basic radio button
williamvinogradov/multiplatform-spike pull request #19
Opened 2022-11-25 04:14 UTC by const314

2022-11-25 09:04 UTC, MikeVitik requested changes

2022-11-25 09:04 UTC, MikeVitik commented on packages/react/src/components/radio-button/radio-button.tsx
> +const DefaultRadioTemplate = React.memo(({ selected }: RadioTemplateProps) => (
Do we really need memo here?

2022-11-25 09:04 UTC, MikeVitik commented on packages/react/src/components/radio-button/types.ts
> +  selected: boolean;
Selected isn't good name. Could we change it to checked?

2022-11-25 09:04 UTC, MikeVitik commented on packages/react/src/components/radio-button/types.ts
> +  payload: PayloadType;
Why payload instead of the more common 'text' or 'label'?

2022-11-25 09:04 UTC, MikeVitik commented on packages/react/src/components/radio-button/radio-button.tsx
> +export const RadioButton = forwardRef<HTMLInputElement, RadioButtonProps>(
Do we really need forwardRef?

2022-11-25 09:04 UTC, MikeVitik commented on packages/react/src/components/radio-button/radio-button.tsx
> +    const RadioComponent = useMemo(
Do we really need memo here?

2022-11-25 09:26 UTC, const314 commented on packages/react/src/components/radio-button/radio-button.tsx
> +const DefaultRadioTemplate = React.memo(({ selected }: RadioTemplateProps) => (
It's unnecessary to rerender this component if the selected prop hasn't changed, so using the memo here seems reasonable.

2022-11-25 09:33 UTC, const314 commented on packages/react/src/components/radio-button/types.ts
> +  payload: PayloadType;
I agree that it's a bit confusing. It can be either string or any react element, so 'text' doesn't look correct here. If we can call 'label' any component that is attached to a radio, then 'label' is a suitable name.

2022-11-25 09:40 UTC, const314 commented on packages/react/src/components/radio-button/radio-button.tsx
> +export const RadioButton = forwardRef<HTMLInputElement, RadioButtonProps>(
If we want to be able to use refs with this component then yes. Functional components should be wrapped in forwardRef to work with refs.

2022-11-25 09:46 UTC, const314 commented on packages/react/src/components/radio-button/radio-button.tsx
> +    const RadioComponent = useMemo(
Using a memo, we can keep the same component on rerenders until the new template passed with props.

2022-11-25 09:59 UTC, const314 commented on packages/react/src/components/radio-button/types.ts
> +  selected: boolean;
fixed

2022-11-25 09:59 UTC, const314 commented on packages/react/src/components/radio-button/types.ts
> +  payload: PayloadType;
fixed, changed to 'label'

2022-11-27 20:56 UTC, williamvinogradov commented on packages/react/src/components/radio-button/radio-button.tsx
> +    const RadioComponent = useMemo(
Maybe, it'll be better to wrap the component into ```React.memo``` once instead of the two ```useMemo``` hooks inside?

2022-11-27 20:58 UTC, williamvinogradov commented
Let's add a simple scss style file to this PR.
Because we need it to test our Inferno generator with SCSS soon.

2022-11-28 07:45 UTC, const314 commented on packages/react/src/components/radio-button/radio-button.tsx
> +    const RadioComponent = useMemo(
removed all memos for now

2022-11-28 07:45 UTC, const314 commented on packages/react/src/components/radio-button/radio-button.tsx
> +const DefaultRadioTemplate = React.memo(({ selected }: RadioTemplateProps) => (
removed all memos for now

2022-11-28 09:26 UTC, MikeVitik approved these changes

2022-11-28 11:09 UTC, williamvinogradov approved these changes

2022-11-28 11:10 UTC, merged