React: connect radio button to core
williamvinogradov/multiplatform-spike pull request #24
Opened 2022-12-01 15:18 UTC by const314

2022-12-02 08:19 UTC, IlyaKhD commented on packages/react/src/components/radio-button/radio-button.tsx
> +    const checked = checkedProp !== undefined ? checkedProp : stateFromContext?.value === value;
🔴 I suggest to rewrite so that 
1) there is no need to modify `useContext`
2) override `checked` property if radio-group context is found

```suggestion
    const radioGroup = useContext(RadioGroupContext);

    const handleOnChange = useCallback(
      (e: React.ChangeEvent) => {
        radioGroup?.dispatcher.dispatch(Actions.updateValue, {
          value,
        });

        onChange?.(e);
      },
      [radioGroup?.dispatcher, onChange, value],
    );

    const inputId = useId();

    const checked = radioGroup
      ? useCoreState(radioGroup.stateManager)?.value === value
      : checkedProp

```

2022-12-02 08:19 UTC, IlyaKhD commented on packages/react/src/internal/hooks/use-core-state.ts
> +): TState | undefined {
🔴 I believe we can keep it strict

```suggestion
  stateManager: StateManager<TState>,
): TState {
```

2022-12-02 08:19 UTC, IlyaKhD commented on packages/react/src/components/radio-button/radio-button.tsx
>  export const RadioButton = forwardRef<HTMLInputElement, RadioButtonProps>(
🟡 Maybe better to reduce nesting here:

```suggestion
export const RadioButton = forwardRef(render);
function render(
  {...} : RadioButtonProps,
  inputRef: ForwardedRef<HTMLInputElement>,
) {
```

2022-12-02 09:02 UTC, MikeVitik requested changes

2022-12-02 09:02 UTC, MikeVitik commented on packages/react/src/components/radio-button/radio-button.tsx
> +} from 'react';
```suggestion
import React, {
  useId, forwardRef, useContext
} from 'react';
```

2022-12-02 09:02 UTC, MikeVitik commented on packages/react/src/components/radio-button/radio-button.tsx
>      return (
Add fully uncontrolled mode

2022-12-02 09:05 UTC, const314 commented on packages/react/src/components/radio-button/radio-button.tsx
> +    const checked = checkedProp !== undefined ? checkedProp : stateFromContext?.value === value;
Unfortunately, we cannot call hooks conditionally, so, useCoreState should be called at the top level

2022-12-02 09:36 UTC, IlyaKhD commented on packages/react/src/components/radio-button/radio-button.tsx
> +    const checked = checkedProp !== undefined ? checkedProp : stateFromContext?.value === value;
Maybe create one more hook to keep conditions inside? Smth like `useExternalState` and use it in such components-inter-op cases? It then will incapsulate these two hooks:

```
    const { stateManager, dispatcher } = useContext(RadioGroupContext) || {};
    const stateFromContext = useCoreState(stateManager);
```

2022-12-02 10:53 UTC, const314 commented on packages/react/src/components/radio-button/radio-button.tsx
> +} from 'react';
fixed

2022-12-02 11:13 UTC, williamvinogradov commented on packages/react/src/components/radio-button/types.ts
> +  value: string | number;
If we decide to restrict the value of the radio group by 'string | number' type for now,
let's restrict the generic parameter in the radio group too.

Something like:

```ts
// somewhere in the common types file
export type RadioGroupValue = string | number;

// restrict the radio group generic parameter
function RadioGroupInternal<T extends RadioGroupValue>(props: RadioGroupProps<T>)
```

2022-12-02 14:09 UTC, const314 commented on packages/react/src/components/radio-button/radio-button.tsx
> +    const checked = checkedProp !== undefined ? checkedProp : stateFromContext?.value === value;
Extracted to a separate hook

2022-12-02 14:24 UTC, const314 commented on packages/react/src/internal/hooks/use-core-state.ts
> +): TState | undefined {
we still need to call this hook with a possible undefined argument.

2022-12-02 14:40 UTC, const314 commented on packages/react/src/components/radio-button/types.ts
> +  value: string | number;
fixed

2022-12-02 14:48 UTC, const314 commented on packages/react/src/components/radio-button/radio-button.tsx
>  export const RadioButton = forwardRef<HTMLInputElement, RadioButtonProps>(
Let's leave it as is for now. We use hooks here, and they should be inside of a component, not the render function.

2022-12-05 11:17 UTC, const314 commented on packages/react/src/internal/hooks/use-core-state.ts
> +): TState | undefined {
fixed

2022-12-05 12:20 UTC, williamvinogradov commented on packages/react/src/components/radio-button/radio-button.tsx
> +const renderRadioButton = ({
🟡 
Following our code style guides, let's use the 'function' keyword instead of the arrow functions at the top level.

E.g.
```ts
const myFunc = () => { ... }; // bad

function myFunc() { ... } // good

function myFunc() {
  function anotherFunc() { ... } // bad
}

function myFunc() {
  const anotherFunc = () => { ... }; // good
}

```

[Link to the code style](https://wiki.devexpress.devx/en/devextreme/workflow/manuals/renovation-2/development)
[Link to the Trello card with examples](https://trello.com/c/ym85e7tP/1263-use-function-or)

2022-12-05 12:20 UTC, williamvinogradov commented on packages/react/src/components/radio-button/radio-button.tsx
> +  const handleOnChange = () => {
Question.

Maybe we need the 'useCallback' hook here?
Or will it be a premature optimization?

2022-12-05 12:20 UTC, williamvinogradov commented on packages/react/src/components/radio-button/types.ts
>  import { ComponentType, ReactElement } from 'react';
🔴
Let's add React to this import.
Because without it we referenced UMD global variable :)

```ts
import React, { ComponentType, ReactElement } from 'react';
```

2022-12-05 12:20 UTC, williamvinogradov commented on packages/react/src/components/radio-button/radio-button.tsx
> -import React, { useId, forwardRef } from 'react';
🔴
Maybe we can use the HoC technique here?

Something like this:
```ts
import React, { useId, forwardRef, useContext } from 'react';
import { Actions } from '@devexpress/components';
import {
  RadioButtonProps,
  LabelTemplateProps,
  RadioTemplateProps,
  RadioButtonRenderProps, CoreBoundRadioButtonProps,
} from './types';
import { RadioGroupContext } from '../radio-group/radio-group-context';
import { useCoreState } from '../../internal/hooks';

type RadioButtonRenderType = (props: RadioButtonRenderProps) => JSX.Element;

const DefaultRadioTemplate = ({ checked = false }: RadioTemplateProps) => (
  <span>{checked ? '◉' : '◎'}</span>
);

const DefaultLabelTemplate = ({ label }: LabelTemplateProps) => (
  <span>{label}</span>
);

function RadioButtonRender({
  name,
  value,
  checked,
  onClick,
  onChange,
  label,
  radioTemplate,
  labelTemplate,
  inputId,
  inputRef,
}: RadioButtonRenderProps) {
  const RadioComponent = radioTemplate || DefaultRadioTemplate;
  const LabelComponent = labelTemplate || DefaultLabelTemplate;

  return (
    <span>
      <label
        htmlFor={inputId}
        style={{ cursor: 'pointer', userSelect: 'none' }}
      >
        <input
          ref={inputRef}
          id={inputId}
          name={name}
          style={{ display: 'none' }}
          type="radio"
          value={value}
          checked={checked}
          onClick={onClick}
          onChange={onChange}
        />
        <RadioComponent checked={checked} />
        {label && <LabelComponent label={label} />}
      </label>
    </span>
  );
}

function withRadioGroup(
  RadioButton: RadioButtonRenderType,
) {
  return (
    props: CoreBoundRadioButtonProps,
  ) => {
    const { radioGroupCore: { dispatcher, stateManager }, ...restProps } = props;
    const coreState = useCoreState(stateManager);

    const checked = coreState.value === restProps.value;
    const handleOnClick = () => {
      dispatcher.dispatch(Actions.updateValue, {
        value: restProps.value,
      });
      return true;
    };

    // TODO: Need to discuss with rule :)
    // eslint-disable-next-line react/jsx-props-no-spreading
    return <RadioButton checked={checked} onClick={handleOnClick} {...restProps} />;
  };
}

export const RadioButton = forwardRef<HTMLInputElement, RadioButtonProps>(
  (props, inputRef) => {
    const radioGroupCore = useContext(RadioGroupContext);
    const inputId = useId();

    return radioGroupCore
      ? withRadioGroup(RadioButtonRender)({
        ...props,
        inputId,
        inputRef,
        radioGroupCore,
      })
      // TODO: Need to discuss with rule :)
      // eslint-disable-next-line react/jsx-props-no-spreading
      : <RadioButtonRender inputId={inputId} inputRef={inputRef} {...props} />;
  },
);

```

2022-12-05 12:20 UTC, williamvinogradov commented on packages/react/src/components/radio-button/radio-button.tsx
> +  const handleOnChange = () => {
Major comment.

Maybe will it be better to use the 'onclick' as a base native event here?

Because the 'onchange' native event will work only inside the form and has a little strange behavior :)
[Link to the CodeSandbox playground](https://codesandbox.io/s/laughing-david-6ltwgn?file=/index.html)

2022-12-05 13:32 UTC, const314 commented on packages/react/src/components/radio-button/radio-button.tsx
>      return (
fixed

2022-12-05 13:35 UTC, const314 commented on packages/react/src/components/radio-button/radio-button.tsx
> +  const handleOnChange = () => {
We discussed it with Mike Vitik earlier and decided that this is a premature optimization, at least for now. I removed useCallback usage in one of the earlier commits.

2022-12-05 13:36 UTC, const314 commented on packages/react/src/components/radio-button/radio-button.tsx
> +const renderRadioButton = ({
Good point, will fix it.

2022-12-05 13:53 UTC, williamvinogradov commented on packages/react/src/components/radio-button/radio-button.tsx
> +  const handleOnChange = () => {
Discussed, my bad, 'onchange' is ok

2022-12-05 14:02 UTC, const314 commented on packages/react/src/components/radio-button/types.ts
>  import { ComponentType, ReactElement } from 'react';
fixed

2022-12-05 14:02 UTC, const314 commented on packages/react/src/components/radio-button/radio-button.tsx
> +const renderRadioButton = ({
fixed

2022-12-05 14:22 UTC, const314 commented on packages/react/src/components/radio-button/radio-button.tsx
> -import React, { useId, forwardRef } from 'react';
rewritten as HOC

2022-12-05 14:54 UTC, IlyaKhD commented on packages/react/src/components/radio-group/radio-group.tsx
> +
🟡 Do we need this type? Maybe better inline it?
```suggestion

```

```ts
function RadioGroupInternal<T extends string | number>
```

2022-12-05 14:54 UTC, IlyaKhD commented on packages/react/src/internal/hooks/use-core-state.ts
> +    };
🟡 Is it possible to unwrap it?

```suggestion
    return unsubscribe;
```

2022-12-05 14:54 UTC, IlyaKhD commented on packages/react/src/components/radio-button/radio-button.tsx
> +  const isUncontrolled = checked === undefined;
🔴 What if `undefined` is provided by intention?

I'm not sure what we can do with it, maybe smth like this:

```ts
function RadioButtonInternal({
  name,
  value,
  defaultChecked,
  onClick,
  onChange,
  label,
  radioTemplate,
  labelTemplate,
  inputId,
  inputRef,
  ...props,
}: RadioButtonRenderProps) {
  const [internalChecked, setInternalChecked] = useState(defaultChecked);

  const RadioComponent = radioTemplate || DefaultRadioTemplate;
  const LabelComponent = labelTemplate || DefaultLabelTemplate;

  const isUncontrolled =  !props.hasOwnProperty('checked');
```

2022-12-05 14:54 UTC, IlyaKhD commented on packages/react/src/components/radio-button/radio-button.tsx
> +  const isUncontrolled = checked === undefined;
🟡 Btw, as for me, better use `isControlled` variable instead

2022-12-05 14:54 UTC, IlyaKhD commented on packages/react/src/components/radio-button/radio-button.tsx
> +        <RadioComponent checked={isUncontrolled ? internalChecked : checked} />
🔴 Shouldn't both `input` and `RadioComponent` use the same `checked` value?

```ts
const checked = isControlled ? props.checked : internalChecked;
```

```jsx
<input checked={checked} />
<RadioComponent checked={checked} />
```

2022-12-05 14:54 UTC, IlyaKhD commented on packages/react/src/components/radio-button/radio-button.tsx
> +  const [internalChecked, setInternalChecked] = useState(defaultChecked);
🔴 I think we can give out narrower type for `checked`

```suggestion
  const [internalChecked, setInternalChecked] = useState(defaultChecked ?? false);
```
If radio-group is in the uncontrolled mode, and no default value provided, then checked is `false`.

This makes it possible to avoid checking for `undefined` in templates:

```ts
export interface RadioTemplateProps {
  checked: boolean;
}
```

2022-12-05 15:06 UTC, const314 commented on packages/react/src/components/radio-group/radio-group.tsx
> +
It is also used in the radio button since the values of a radio and a group should be of the same type

2022-12-05 15:14 UTC, const314 commented on packages/react/src/components/radio-button/radio-button.tsx
> +        <RadioComponent checked={isUncontrolled ? internalChecked : checked} />
No, in this case, if the component is uncontrolled, checked should also be undefined in the input to make it manage the state internally.
But the radio component should display the check mark that came from the onChanged event in this case.

2022-12-05 15:16 UTC, const314 commented on packages/react/src/components/radio-button/radio-button.tsx
> +  const [internalChecked, setInternalChecked] = useState(defaultChecked);
If checked is set to false, defaultChecked is ignored by input. So, it should be left undefined in uncontrolled mode.

2022-12-05 15:17 UTC, const314 commented on packages/react/src/components/radio-button/radio-button.tsx
> +  const isUncontrolled = checked === undefined;
Event if checked={undefined} provided by intension, it just means that the component is uncontrolled.

2022-12-05 15:20 UTC, const314 commented on packages/react/src/internal/hooks/use-core-state.ts
> +    };
fixed

2022-12-06 07:31 UTC, MikeVitik commented on packages/react/src/components/radio-button/radio-button.tsx
> +  const [internalChecked, setInternalChecked] = useState(defaultChecked);
Move all controlled logic to separate HOC. Because if the radio button is uncontrolled we do not use useState at all.

2022-12-06 07:32 UTC, MikeVitik requested changes
Introduce HOC for incapsulate uncontrolled logic

2022-12-06 08:36 UTC, const314 commented on packages/react/src/components/radio-button/radio-button.tsx
> +  const [internalChecked, setInternalChecked] = useState(defaultChecked);
fixed

2022-12-06 09:11 UTC, IlyaKhD commented on packages/react/src/components/radio-button/types.ts
> +  checked?: boolean;
Let's try make it non-optional

2022-12-06 09:17 UTC, const314 commented on packages/react/src/components/radio-button/types.ts
> +  checked?: boolean;
fixed

2022-12-06 09:36 UTC, IlyaKhD approved these changes

2022-12-06 11:27 UTC, williamvinogradov approved these changes

2022-12-06 11:42 UTC, MikeVitik approved these changes

2022-12-06 11:51 UTC, merged