Core framework alpha: implement utils + jest unit tests.
williamvinogradov/multiplatform-spike pull request #7
Opened 2022-11-03 15:04 UTC by williamvinogradov

2022-11-04 09:08 UTC, MikeVitik requested changes

2022-11-04 10:08 UTC, IlyaKhD commented on packages/core/src/utils/observable.ts
> +}
Can this be deleted?
```suggestion
```

2022-11-04 10:08 UTC, IlyaKhD commented on packages/core/src/utils/observable.ts
> +    return () => { listeners = listeners.filter((listener) => listener !== newListener); };
We can avoid creating arrays here using `indexOf`+`splice` or maybe using `Set`:

```
let listeners: Se<T>[] = [];
```

```suggestion
    listeners.add(newListener);

    return () => { listeners.delete(newListener) };
```

2022-11-04 10:08 UTC, IlyaKhD commented on packages/core/src/utils/__test__/observable.test.ts
> +describe('Core: Utils: observable', () => {
Add tests for subscribing/unsubscribing the same multiple times:

```
const unsubscribe1 = observable.subscribe(spySubscriber);
const unsubscribe2 = observable.subscribe(spySubscriber);
// ...
unsubscribe1();
// ...
unsubscribe2();
// ...
```

2022-11-04 10:18 UTC, williamvinogradov commented on packages/core/src/utils/cache.ts
> +type Func = (...args: any[]) => any;
We cannot use unknown here, because:
```ts
type Func = (...args: unknown[]) => unknown;

// TS2322: Type '(a: number, b: number) => { result: number; }' is not assignable to type 'Func'.   Types of parameters // 'a' and 'args' are incompatible. 
// Type 'unknown' is not assignable to type 'number'.
const funcToCache: Func = (a: number, b: number) => ({
  result: a + b,
});
```

2022-11-04 11:13 UTC, williamvinogradov commented on packages/core/src/utils/cache.ts
> +  let isFirstCall = true;
Fixed

2022-11-04 11:13 UTC, williamvinogradov commented on packages/core/src/utils/comparers/shadowComparer.ts
> +  return !prevKeys.find((key) => prevObj[key] !== nextObj[key]);
Fixed

2022-11-04 11:13 UTC, williamvinogradov commented on packages/core/src/utils/__test__/getKeys.test.ts
> +  test('It should returns key array of the passed object', () => {
Fixed typo

2022-11-04 11:13 UTC, williamvinogradov commented on packages/core/src/utils/getKeys.ts
> +const getKeys = <T extends object>(object: T) => Object.keys(object) as (keyof T)[];
Your version loses not string keys of the object.

I suggest the next solution with better typings:
```ts
type NotArray<T> = object & Exclude<T, unknown[]>;
type NotFunction<T> = object & Exclude<T, FunctionType>;
type ObjectType<T> = NotArray<T> & NotFunction<T>;

const getKeys = <T>(object: ObjectType<T>) => Object.keys(object) as (keyof T)[];
```

Also, I moved these types to separate types.ts for reuse :)

2022-11-04 11:13 UTC, williamvinogradov commented on packages/core/src/utils/__test__/cache.test.ts
> +    const spyFunc = fn().mockReturnValue({ result: 4 });
Agree with you, removed this

2022-11-04 11:13 UTC, williamvinogradov commented on packages/core/src/utils/__test__/cache.test.ts
> +    const cachedFunc = createCache(() => 4, spyComparer);
Why object instead of a number?
In this case, the return value doesn't matter.
So, it may be a random number, object, or whatever :)

2022-11-04 11:13 UTC, williamvinogradov commented on packages/core/src/utils/__test__/cache.test.ts
> +  });
Agree with you, I fixed it.

2022-11-04 11:13 UTC, williamvinogradov commented on packages/core/src/utils/__test__/cache.test.ts
> +  });
Agree with you, I fixed it.

2022-11-04 11:13 UTC, williamvinogradov commented on packages/core/src/utils/__test__/cache.test.ts
> +  test('It should call always call comparer, except first call', () => {
Fixed typo

2022-11-04 11:13 UTC, williamvinogradov commented on packages/core/src/utils/__test__/cache.test.ts
> +    const cachedFunc = createCache(funcToCache, testComparer);
Agree with you, I fixed it.

2022-11-04 11:13 UTC, williamvinogradov commented on packages/core/src/utils/__test__/cache.test.ts
> +    expect(firstResult === secondResult).toBeTruthy();
Agree with you, I fixed it.

2022-11-04 11:13 UTC, williamvinogradov commented on packages/core/src/utils/__test__/cache.test.ts
> +    expect(firstResult !== secondResult).toBeTruthy();
Agree with you, I fixed it.

2022-11-04 11:13 UTC, williamvinogradov commented on packages/core/src/utils/__test__/cache.test.ts
> +    const cachedFunc = createCache(funcToCache, testComparer);
Agree with you, I fixed it.

2022-11-04 11:13 UTC, williamvinogradov commented on packages/core/src/utils/__test__/observable.test.ts
> +    expect(spySubscriber).toHaveBeenCalledTimes(1);
I think it's will be better to write a separate test case for this.
Fixed.

2022-11-04 11:13 UTC, williamvinogradov commented on packages/core/src/utils/observable.ts
> +}
It will be used in the state.ts in the future.
We can remove it and add it in the future.
But, in my point of view, we can leave it in this PR.

2022-11-04 11:13 UTC, williamvinogradov commented on packages/core/src/utils/observable.ts
> +}
It's an important interface that will be used in future code.
By default, the 'create observable' returns an object that contains the 'emit' method.
We need it to emit new values to subscribers from the other parts of the code.
But, if we pass observable outside of the inner core framework code, the 'emit' method should be unreachable.

2022-11-04 11:13 UTC, williamvinogradov commented on packages/core/src/utils/observable.ts
> +    return () => { listeners = listeners.filter((listener) => listener !== newListener); };
Agree with you.
Changing listeners to the Set instead of the Array will be cool because it solves the problem when the same function is passed to the subscribe multiple times.

2022-11-04 11:14 UTC, williamvinogradov commented on packages/core/src/utils/__test__/observable.test.ts
> +describe('Core: Utils: observable', () => {
Added some new test cases for the same function passed into subscribe method.

2022-11-04 11:27 UTC, nightskylark commented on packages/core/src/utils/cache.ts
> +  };
Not sure my solution is better but take a look please
```suggestion
  let cachedArg: Parameters<TFunction>;
  let cachedResult: ReturnType<TFunction>;

  const callAndCache =  (...arg: Parameters<TFunction>) => {
    cachedArg = arg;
    return cachedResult = func(...arg) as ReturnType<TFunction>;
  };

  const callCached = (...arg: Parameters<TFunction>) => {
    return comparer(cachedArg, arg)
        ? cachedResult
        : callAndCache(...arg) as ReturnType<TFunction>;
  };

  let result = (...arg: Parameters<TFunction>) => {
    result = callCached;
    return callAndCache(...arg) as ReturnType<TFunction>;
  };

  return (...arg: Parameters<TFunction>) => result(...arg) as ReturnType<TFunction>;
```

2022-11-04 13:21 UTC, IlyaKhD commented on packages/core/src/utils/getKeys.ts
> +const getKeys = <T extends object>(object: T) => Object.keys(object) as (keyof T)[];
> Your version loses not string keys of the object.

I thought this is what intended. Do we really need non-string keys? Could you give an example?

2022-11-04 13:25 UTC, IlyaKhD commented on packages/core/src/utils/__test__/cache.test.ts
> +    const cachedFunc = createCache(() => 4, spyComparer);
Moreover 4 - can be definitely called a `magic number`, but I never heard `{}` is called 'a magic object' or `a magic value`

2022-11-04 13:26 UTC, IlyaKhD commented on packages/core/src/utils/observable.ts
> +}
I prefer to remove it from this PR so that we can review the interface when its usage is clear

2022-11-04 13:27 UTC, IlyaKhD commented on packages/core/src/utils/observable.ts
> +}
Same thing - let's add types interfaces and other stuff when usage examples are clear

2022-11-04 13:28 UTC, IlyaKhD commented on packages/core/src/utils/__test__/cache.test.ts
> +    const cachedFunc = createCache(() => 4, spyComparer);
Now I get an idea that the best way to define a 'random' function is to use `fn()`
How do you think?

2022-11-04 13:29 UTC, IlyaKhD commented on packages/core/src/utils/observable.ts
> +}
Otherwise I can't review it - I don't understand what  it is used for and what shape should it have

2022-11-07 09:13 UTC, williamvinogradov commented on packages/core/src/utils/cache.ts
> +  };
I look into your solution and agree with you that is a cool technic.
Maybe, it's a little more complicated than mine, but let's try it.

I will push my variant of this idea.

2022-11-07 09:15 UTC, IlyaKhD commented on packages/core/src/utils/cache.ts
> +  };
```suggestion
  return (...args: Parameters<TFunction>) => {
    if (cachedArg !== undefined && comparer(cachedArgs, args)) {
      return cachedResult;
    }

    cachedArgs = args;
    cachedResult = func(...args) as ReturnType<TFunction>;

    return cachedResult;
  };
```

2022-11-07 09:19 UTC, MikeVitik approved these changes, later dismissed

2022-11-07 09:29 UTC, williamvinogradov commented on packages/core/src/utils/cache.ts
> +  comparer: (prev: Parameters<TFunction>, next: Parameters<TFunction>) => boolean,
Agree with you, fixed.

2022-11-07 09:30 UTC, williamvinogradov commented on packages/core/src/utils/observable.ts
> +}
We discussed it and decided to remove unused types.
We'll add this type later with real usage.

2022-11-07 09:30 UTC, williamvinogradov commented on packages/core/src/utils/observable.ts
> +}
We discussed it and decided to remove unused types.
We'll add this type later with real usage.

2022-11-07 09:54 UTC, IlyaKhD commented on packages/core/src/utils/__test__/shadowComparer.test.ts
> +  it('Should return false if passed values have different js types', () => {
```suggestion
  it('returns false for arguments of different type', () => {
```

2022-11-07 09:54 UTC, IlyaKhD commented on packages/core/src/utils/__test__/shadowComparer.test.ts
> +  });
```suggestion
  it('compares numbers`, () => {
    expect(shadowComparer(2, 2)).toBeTruthy();
    expect(shadowComparer(2, 3)).toBeFalsy();
  });
  
  it('compares booleans', () => {
    expect(shadowComparer(true, true)).toBeTruthy();
    expect(shadowComparer(false, false)).toBeTruthy();
    expect(shadowComparer(true, false)).toBeFalsy();
    expect(shadowComparer(false, true)).toBeFalsy();
  });
  
   it('compares functions', () => {
     const firstFunc = () => {};
     const secondFunc = () => {};
     expect(shadowComparer(firstFunc, firstFunc)).toBeTruthy();
     expect(shadowComparer(firstFunc, secondFunc)).toBeFalsy();
  });
```

2022-11-07 09:54 UTC, IlyaKhD commented on packages/core/src/utils/__test__/shadowComparer.test.ts
> +  });
I think we should add test cases for `Date`

2022-11-07 09:54 UTC, IlyaKhD commented on packages/core/src/utils/__test__/shadowComparer.test.ts
> +  it('Should return false if keys count aren\'t equal', () => {
```suggestion
  it('returns false if keys count aren\'t equal', () => {
```

2022-11-07 09:54 UTC, IlyaKhD commented on packages/core/src/utils/__test__/shadowComparer.test.ts
> +  it('Should return true if all keys on the first level are equal', () => {
```suggestion
  it('returns true if all keys on the first level are equal', () => {
```

2022-11-07 09:54 UTC, IlyaKhD commented on packages/core/src/utils/__test__/shadowComparer.test.ts
> +    };
No need for a type here
```suggestion
```

2022-11-07 09:54 UTC, IlyaKhD commented on packages/core/src/utils/__test__/shadowComparer.test.ts
> +  it('Should return false if some keys on the first level are different', () => {
```suggestion
  it('returns false if some keys on the first level are different', () => {
```

2022-11-07 09:54 UTC, IlyaKhD commented on packages/core/src/utils/__test__/shadowComparer.test.ts
> +  it('Should compare only first level keys', () => {
```suggestion
  it('compares only first level keys', () => {
```

2022-11-07 09:54 UTC, IlyaKhD commented on packages/core/src/utils/__test__/shadowComparer.test.ts
> +    };
No need for a type
```suggestion
    type Test = {
      a: {
        b: boolean,
      }
    };
```

2022-11-07 09:54 UTC, IlyaKhD commented on packages/core/src/utils/shadowComparer.ts
> +  }
```suggestion
  if (typeof prev !== typeof next) {
    return false;
  }
```

2022-11-07 09:54 UTC, IlyaKhD commented on packages/core/src/utils/shadowComparer.ts
> +  const isFunctionTypes = typeof prev === 'function' && typeof next === 'function';
Either use 'is...' notation for all variables, or better -  let's drop it)
```suggestion
  const functionTypes = typeof prev === 'function' && typeof next === 'function';
```

2022-11-07 09:54 UTC, IlyaKhD commented on packages/core/src/utils/shadowComparer.ts
> +  const nextObj = next as { [index: string]: unknown };
I think prev/next maybe confusing - it's not necessary that one follows another in some sequence

```suggestion
  const a = prev as { [index: string]: unknown };
  const b = next as { [index: string]: unknown };
```
Maybe `objA`, `objB`, or smth like.

2022-11-07 10:01 UTC, williamvinogradov commented on packages/core/src/utils/cache.ts
> +  };
Okay, let's discuss it with @nightskylark  and choose a final solution
For me both of these variants are equal

2022-11-07 10:04 UTC, williamvinogradov commented on packages/core/src/utils/__test__/shadowComparer.test.ts
> +  it('Should return false if passed values have different js types', () => {
Ok, let's rename this test case.

2022-11-07 10:10 UTC, williamvinogradov commented on packages/core/src/utils/shadowComparer.ts
> +  const nextObj = next as { [index: string]: unknown };
Let's name it ```firstValue``` and ```secondValue```

2022-11-07 10:12 UTC, williamvinogradov commented on packages/core/src/utils/shadowComparer.ts
> +  }
I do not agree with you here.
I think my version reads better.

2022-11-07 10:14 UTC, williamvinogradov commented on packages/core/src/utils/__test__/shadowComparer.test.ts
> +    };
I do not agree with you here.
From my point of view, with types, these tests are better read.

2022-11-07 10:15 UTC, williamvinogradov commented on packages/core/src/utils/__test__/shadowComparer.test.ts
> +  it('Should compare only first level keys', () => {
Fixed naming in all test cases.

2022-11-07 10:15 UTC, williamvinogradov commented on packages/core/src/utils/__test__/shadowComparer.test.ts
> +    };
I do not agree with you here.
From my point of view, with types, these tests are better read.

2022-11-07 10:15 UTC, williamvinogradov commented on packages/core/src/utils/__test__/shadowComparer.test.ts
> +  it('Should return true if all keys on the first level are equal', () => {
Fixed naming in all test cases

2022-11-07 10:15 UTC, williamvinogradov commented on packages/core/src/utils/__test__/shadowComparer.test.ts
> +  it('Should return false if keys count aren\'t equal', () => {
Fied naming in all test cases

2022-11-07 10:27 UTC, williamvinogradov commented on packages/core/src/utils/__test__/shadowComparer.test.ts
> +  });
I don't agree with you here.
All value types in shadowComparer compare the same way.
So, I don't think that we should write test cases for all of these types.

But, dates have a specific comparison, so, I added a special case for it.

2022-11-07 10:28 UTC, williamvinogradov commented on packages/core/src/utils/cache.ts
> +type Func = (...args: any[]) => any;
@MikeVitik, if you agree with me that 'any' type is okay here, please resolve this comment :)

2022-11-07 10:29 UTC, williamvinogradov commented on packages/core/src/utils/__test__/shadowComparer.test.ts
> +  it('Should return false if some keys on the first level are different', () => {
Fixed namings in all test cases.

2022-11-07 10:37 UTC, IlyaKhD commented on packages/core/src/utils/__test__/shadowComparer.test.ts
> +  });
> All value types in shadowComparer compare the same way.

But tests know nothing about implementation, right?

2022-11-07 10:42 UTC, IlyaKhD commented on packages/core/src/utils/__test__/shadowComparer.test.ts
> +    };
This type is not important for what the test checks, so it brings in some extra information.
Since this information does not clarify anything it's a kind of noise.

Test should be as small as possible, I think

2022-11-07 10:49 UTC, IlyaKhD commented on packages/core/src/utils/cache.ts
> +  };
In this case I prefer 'less code is better' principle.
Caching is a standard algorithm, we should keep it simple

2022-11-07 11:19 UTC, IlyaKhD commented on packages/core/src/utils/cache.ts
> +  };
@nightskylark, how do you think?

2022-11-07 11:31 UTC, williamvinogradov commented on packages/core/src/utils/__test__/shadowComparer.test.ts
> +  });
We discussed and decided that we will leave this test as it is
Since we do not want to write tests for all data types

Also, a special handle case for Date values has been added

2022-11-07 11:32 UTC, williamvinogradov commented on packages/core/src/utils/__test__/shadowComparer.test.ts
> +    };
Discussed and decided that this type should be removed from the test

2022-11-07 11:32 UTC, williamvinogradov commented on packages/core/src/utils/__test__/shadowComparer.test.ts
> +    };
Discussed and decided that this type should be removed from the test

2022-11-07 11:38 UTC, nightskylark commented on packages/core/src/utils/cache.ts
> +  };
Choose something guys. Such changes should not take many discussions.

2022-11-07 11:54 UTC, MikeVitik approved these changes

2022-11-07 12:25 UTC, IlyaKhD approved these changes

2022-11-07 12:28 UTC, merged